import os, yaml

# base dir is the one containing the config file, paths should be relative to it
BASE_PATH = os.path.dirname(os.path.abspath(__file__))

MODELS_PATH = os.path.join(BASE_PATH, '../../models_dot')
RESULTS_PATH = os.path.join(BASE_PATH, '../../results')

# 128 MB allocation as maximum for viz.js
VIZJS_MAX_RAM = 256*1024*1024

# set up logging
with open(os.path.join(BASE_PATH, "logging.conf")) as f:
    LOGGING_CONFIG = yaml.load(f)

# generated by os.urandom(24) - necessary to sign client cookies so they can't forge variables
SECRET_KEY = b'I\x9c\xda\xe7\x18\x88\x91Y\xfe\x04R\xb5\xecjfO\x02\xdak\x80\x89C\x0cF'

del os
del yaml